<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

class RwandaLocationsSeeder extends Seeder
{
    public function run(): void
    {
        $rwanda = Location::create([
            'type' => Location::TYPE_COUNTRY,
            'name' => 'Rwanda',
            'code' => 'RW',
        ]);

        $districts = [
            'Nyarugenge' => [
                'Gitega' => ['Akabahizi' => ['Amahoro', 'Ubumwe'], 'Gatare' => ['Inkingi', 'Isangano']],
                'Kanyinya' => ['Kabuga' => ['Gasabo', 'Kigali'], 'Kimironko' => ['Nyabisindu', 'Remera']],
                'Kigali' => ['Nyamirambo' => ['Biryogo', 'Mumena'], 'Rwezamenyo' => ['Nyakabanda', 'Nyarurama']],
                'Mageragere' => ['Gihanga' => ['Ruhango', 'Rwimbogo'], 'Nyanza' => ['Kagarama', 'Kinyinya']],
                'Muhima' => ['Ubumwe' => ['Amahoro', 'Ingenzi'], 'Umucyo' => ['Ikaze', 'Urugwiro']],
                'Nyakabanda' => ['Amahoro' => ['Ingabo', 'Intsinzi'], 'Biryogo' => ['Impala', 'Isonga']],
                'Nyamirambo' => ['Mumena' => ['Agasharu', 'Ituze'], 'Rugarama' => ['Inkurunziza', 'Inyange']],
                'Nyarugenge' => ['Rwampara' => ['Isangano', 'Umutekano'], 'Urugwiro' => ['Icyizere', 'Ineza']],
                'Rwezamenyo' => ['Gitega' => ['Gasabo', 'Rugando'], 'Nyakabanda' => ['Ubwiza', 'Urumuri']],
            ],
            'Gasabo' => [
                'Bumbogo' => ['Gasanze' => ['Amahoro', 'Icyerekezo'], 'Nyabugogo' => ['Imena', 'Iterambere']],
                'Gatsata' => ['Karuruma' => ['Akabeza', 'Nyagasozi'], 'Nyamabuye' => ['Ingenzi', 'Umushumba']],
                'Gikomero' => ['Murambi' => ['Amizero', 'Imena'], 'Rubona' => ['Igihozo', 'Intego']],
                'Gisozi' => ['Ruhango' => ['Amahoro', 'Urugwiro'], 'Umutekano' => ['Imena', 'Ituze']],
                'Jabana' => ['Gasagara' => ['Intore', 'Ubumwe'], 'Rugende' => ['Ihirwe', 'Imena']],
                'Jali' => ['Kibungo' => ['Amahoro', 'Imena'], 'Musenyi' => ['Icyerekezo', 'Intsinzi']],
                'Kacyiru' => ['Kamatamu' => ['Ubumwe', 'Urugwiro'], 'Kamutwa' => ['Imena', 'Ingenzi']],
                'Kimihurura' => ['Kamukina' => ['Amahoro', 'Imena'], 'Rugando' => ['Ikirezi', 'Umucyo']],
                'Kimironko' => ['Bibare' => ['Imena', 'Ubumwe'], 'Kibagabaga' => ['Amahoro', 'Intore']],
                'Kinyinya' => ['Kagugu' => ['Amahoro', 'Imena'], 'Kajevuba' => ['Icyizere', 'Intsinzi']],
                'Ndera' => ['Masoro' => ['Amahoro', 'Imena'], 'Musave' => ['Icyerekezo', 'Ingenzi']],
                'Nduba' => ['Gasagara' => ['Amahoro', 'Imena'], 'Shango' => ['Ihirwe', 'Intore']],
                'Remera' => ['Nyabisindu' => ['Amahoro', 'Imena'], 'Rukiri' => ['Icyizere', 'Ubumwe']],
                'Rusororo' => ['Kabuga' => ['Amahoro', 'Imena'], 'Masizi' => ['Ingenzi', 'Intsinzi']],
                'Rutunga' => ['Kabuye' => ['Amahoro', 'Imena'], 'Munini' => ['Icyerekezo', 'Intore']],
            ],
            'Kicukiro' => [
                'Gahanga' => ['Nunga' => ['Amahoro', 'Imena'], 'Rwabutenge' => ['Icyerekezo', 'Intore']],
                'Gatenga' => ['Gatenga' => ['Amahoro', 'Imena'], 'Nyanza' => ['Ingenzi', 'Intsinzi']],
                'Gikondo' => ['Kinunga' => ['Amahoro', 'Imena'], 'Kumukenke' => ['Icyizere', 'Ubumwe']],
                'Kagarama' => ['Kagarama' => ['Amahoro', 'Imena'], 'Nyarurama' => ['Ingenzi', 'Intore']],
                'Kanombe' => ['Busanza' => ['Amahoro', 'Imena'], 'Kabeza' => ['Icyerekezo', 'Intsinzi']],
                'Kicukiro' => ['Kagunga' => ['Amahoro', 'Imena'], 'Ngoma' => ['Ingenzi', 'Ubumwe']],
                'Kigarama' => ['Kigarama' => ['Amahoro', 'Imena'], 'Nyarugunga' => ['Icyizere', 'Intore']],
                'Masaka' => ['Ayabaraya' => ['Amahoro', 'Imena'], 'Rusheshe' => ['Ingenzi', 'Intsinzi']],
                'Niboye' => ['Niboye' => ['Amahoro', 'Imena'], 'Gatare' => ['Icyerekezo', 'Ubumwe']],
                'Nyarugunga' => ['Nonko' => ['Amahoro', 'Imena'], 'Kamashashi' => ['Ingenzi', 'Intore']],
            ],
            'Bugesera' => [
                'Gashora' => ['Kamabuye' => ['Amahoro', 'Imena'], 'Ramiro' => ['Icyerekezo', 'Intore']],
                'Juru' => ['Nyamata' => ['Amahoro', 'Imena'], 'Ruhuha' => ['Ingenzi', 'Intsinzi']],
                'Kamabuye' => ['Biryogo' => ['Amahoro', 'Imena'], 'Gakomeye' => ['Icyizere', 'Ubumwe']],
                'Mareba' => ['Biharagu' => ['Amahoro', 'Imena'], 'Cyugaro' => ['Ingenzi', 'Intore']],
                'Mayange' => ['Bushenyi' => ['Amahoro', 'Imena'], 'Kayenzi' => ['Icyerekezo', 'Intsinzi']],
                'Musenyi' => ['Gahengeri' => ['Amahoro', 'Imena'], 'Ntarama' => ['Ingenzi', 'Ubumwe']],
                'Mwogo' => ['Kabuye' => ['Amahoro', 'Imena'], 'Nyamiyaga' => ['Icyizere', 'Intore']],
                'Ngeruka' => ['Kibungo' => ['Amahoro', 'Imena'], 'Rilima' => ['Ingenzi', 'Intsinzi']],
                'Ntarama' => ['Cyugaro' => ['Amahoro', 'Imena'], 'Ntarama' => ['Icyerekezo', 'Ubumwe']],
                'Nyamata' => ['Kanazi' => ['Amahoro', 'Imena'], 'Nyamata' => ['Ingenzi', 'Intore']],
                'Nyarugenge' => ['Gashora' => ['Amahoro', 'Imena'], 'Kamabuye' => ['Icyizere', 'Intsinzi']],
                'Rilima' => ['Biryogo' => ['Amahoro', 'Imena'], 'Rilima' => ['Ingenzi', 'Ubumwe']],
                'Ruhuha' => ['Murama' => ['Amahoro', 'Imena'], 'Ruhuha' => ['Icyerekezo', 'Intore']],
                'Rweru' => ['Nyaburiba' => ['Amahoro', 'Imena'], 'Rweru' => ['Ingenzi', 'Intsinzi']],
                'Shyara' => ['Kibungo' => ['Amahoro', 'Imena'], 'Shyara' => ['Icyizere', 'Ubumwe']],
            ],
            'Gatsibo' => [
                'Gasange' => ['Gasange' => ['Amahoro', 'Imena'], 'Murama' => ['Icyerekezo', 'Intore']],
                'Gatsibo' => ['Gatsibo' => ['Amahoro', 'Imena'], 'Remera' => ['Ingenzi', 'Intsinzi']],
                'Gitoki' => ['Nyagasozi' => ['Amahoro', 'Imena'], 'Rutare' => ['Icyizere', 'Ubumwe']],
                'Kabarore' => ['Kabarore' => ['Amahoro', 'Imena'], 'Rwimbogo' => ['Ingenzi', 'Intore']],
                'Kageyo' => ['Kageyo' => ['Amahoro', 'Imena'], 'Matimba' => ['Icyerekezo', 'Intsinzi']],
                'Kiramuruzi' => ['Kiramuruzi' => ['Amahoro', 'Imena'], 'Nyagasozi' => ['Ingenzi', 'Ubumwe']],
                'Kiziguro' => ['Kiziguro' => ['Amahoro', 'Imena'], 'Rukira' => ['Icyizere', 'Intore']],
                'Muhura' => ['Muhura' => ['Amahoro', 'Imena'], 'Nyagasozi' => ['Ingenzi', 'Intsinzi']],
                'Murambi' => ['Murambi' => ['Amahoro', 'Imena'], 'Nyagisozi' => ['Icyerekezo', 'Ubumwe']],
                'Ngarama' => ['Ngarama' => ['Amahoro', 'Imena'], 'Rugarama' => ['Ingenzi', 'Intore']],
                'Nyagihanga' => ['Nyagihanga' => ['Amahoro', 'Imena'], 'Rwimbogo' => ['Icyizere', 'Intsinzi']],
                'Remera' => ['Remera' => ['Amahoro', 'Imena'], 'Rugarama' => ['Ingenzi', 'Ubumwe']],
                'Rugarama' => ['Rugarama' => ['Amahoro', 'Imena'], 'Rwimbogo' => ['Icyerekezo', 'Intore']],
                'Rwimbogo' => ['Rwimbogo' => ['Amahoro', 'Imena'], 'Nyagasozi' => ['Ingenzi', 'Intsinzi']],
            ],
            'Kayonza' => [
                'Gahini' => ['Gahini' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Kabare' => ['Kabare' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Kabarondo' => ['Kabarondo' => ['Amahoro', 'Imena'], 'Rubona' => ['Icyizere', 'Ubumwe']],
                'Mukarange' => ['Mukarange' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Murama' => ['Murama' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Murundi' => ['Murundi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Mwiri' => ['Mwiri' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Ndego' => ['Ndego' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Nyamirama' => ['Nyamirama' => ['Amahoro', 'Imena'], 'Rubona' => ['Icyerekezo', 'Ubumwe']],
                'Rukara' => ['Rukara' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Ruramira' => ['Ruramira' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intsinzi']],
                'Rwinkwavu' => ['Rwinkwavu' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
            ],
            'Kirehe' => [
                'Gahara' => ['Gahara' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Gatore' => ['Gatore' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Kigarama' => ['Kigarama' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Kigina' => ['Kigina' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Kirehe' => ['Kirehe' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Mahama' => ['Mahama' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Mpanga' => ['Mpanga' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Musaza' => ['Musaza' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Mushikiri' => ['Mushikiri' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Ubumwe']],
                'Nasho' => ['Nasho' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Nyamugari' => ['Nyamugari' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intsinzi']],
                'Nyarubuye' => ['Nyarubuye' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
            ],
            'Ngoma' => [
                'Gashanda' => ['Gashanda' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Jarama' => ['Jarama' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Karembo' => ['Karembo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Kazo' => ['Kazo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Kibungo' => ['Kibungo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Mugesera' => ['Mugesera' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Murama' => ['Murama' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Mutenderi' => ['Mutenderi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Remera' => ['Remera' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Ubumwe']],
                'Rukira' => ['Rukira' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Rukumberi' => ['Rukumberi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intsinzi']],
                'Rurenge' => ['Rurenge' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Sake' => ['Sake' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Zaza' => ['Zaza' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
            ],
            'Nyagatare' => [
                'Gatunda' => ['Gatunda' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Karama' => ['Karama' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Karangazi' => ['Karangazi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Katabagemu' => ['Katabagemu' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Kiyombe' => ['Kiyombe' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Matimba' => ['Matimba' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Mimuli' => ['Mimuli' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Mukama' => ['Mukama' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Musheri' => ['Musheri' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Ubumwe']],
                'Nyagatare' => ['Nyagatare' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Rukomo' => ['Rukomo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intsinzi']],
                'Rwempasha' => ['Rwempasha' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Rwimiyaga' => ['Rwimiyaga' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Tabagwe' => ['Tabagwe' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
            ],
            'Rwamagana' => [
                'Fumbwe' => ['Fumbwe' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Gahengeri' => ['Gahengeri' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Gishari' => ['Gishari' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Karenge' => ['Karenge' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Kigabiro' => ['Kigabiro' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Muhazi' => ['Muhazi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Munyaga' => ['Munyaga' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Munyiginya' => ['Munyiginya' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Mwulire' => ['Mwulire' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Ubumwe']],
                'Nyakariro' => ['Nyakariro' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Nzige' => ['Nzige' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intsinzi']],
                'Rubona' => ['Rubona' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Rwamagana' => ['Rwamagana' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
            ],
            'Huye' => [
                'Gishamvu' => ['Gishamvu' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Huye' => ['Huye' => ['Amahoro', 'Imena'], 'Tumba' => ['Ingenzi', 'Intsinzi']],
                'Karama' => ['Karama' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Kigoma' => ['Kigoma' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Kinazi' => ['Kinazi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Maraba' => ['Maraba' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Mbazi' => ['Mbazi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Mukura' => ['Mukura' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Ngoma' => ['Ngoma' => ['Amahoro', 'Imena'], 'Tumba' => ['Icyerekezo', 'Ubumwe']],
                'Ruhashya' => ['Ruhashya' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Rusatira' => ['Rusatira' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intsinzi']],
                'Rwaniro' => ['Rwaniro' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Simbi' => ['Simbi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Tumba' => ['Tumba' => ['Amahoro', 'Imena'], 'Ngoma' => ['Ingenzi', 'Intsinzi']],
            ],
            'Gisagara' => [
                'Gikonko' => ['Gikonko' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Gishubi' => ['Gishubi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Kansi' => ['Kansi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Kibilizi' => ['Kibilizi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Kigembe' => ['Kigembe' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Mamba' => ['Mamba' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Muganza' => ['Muganza' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Mugombwa' => ['Mugombwa' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Mukindo' => ['Mukindo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Ubumwe']],
                'Musha' => ['Musha' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Ndora' => ['Ndora' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intsinzi']],
                'Nyanza' => ['Nyanza' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Save' => ['Save' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
            ],
            'Kamonyi' => [
                'Gacurabwenge' => ['Gacurabwenge' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Karama' => ['Karama' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Kayenzi' => ['Kayenzi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Kayumbu' => ['Kayumbu' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Mugina' => ['Mugina' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Musambira' => ['Musambira' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Ngamba' => ['Ngamba' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Nyamiyaga' => ['Nyamiyaga' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Nyarubaka' => ['Nyarubaka' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Ubumwe']],
                'Rugarika' => ['Rugarika' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Rukoma' => ['Rukoma' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intsinzi']],
                'Runda' => ['Runda' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
            ],
            'Muhanga' => [
                'Cyeza' => ['Cyeza' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Kabacuzi' => ['Kabacuzi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Kibangu' => ['Kibangu' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Kiyumba' => ['Kiyumba' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Muhanga' => ['Muhanga' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Mushishiro' => ['Mushishiro' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Nyabinoni' => ['Nyabinoni' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Nyamabuye' => ['Nyamabuye' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Nyarusange' => ['Nyarusange' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Ubumwe']],
                'Rongi' => ['Rongi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Rugendabari' => ['Rugendabari' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intsinzi']],
                'Shyogwe' => ['Shyogwe' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
            ],
            'Nyamagabe' => [
                'Buruhukiro' => ['Buruhukiro' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Cyanika' => ['Cyanika' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Gatare' => ['Gatare' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Kaduha' => ['Kaduha' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Kamegeri' => ['Kamegeri' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Kibirizi' => ['Kibirizi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Kibumbwe' => ['Kibumbwe' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Kitabi' => ['Kitabi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Mbazi' => ['Mbazi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Ubumwe']],
                'Mugano' => ['Mugano' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Musange' => ['Musange' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intsinzi']],
                'Musebeya' => ['Musebeya' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Mushubi' => ['Mushubi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Nkomane' => ['Nkomane' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Tare' => ['Tare' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Uwinkingi' => ['Uwinkingi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
            ],
            'Nyanza' => [
                'Busasamana' => ['Busasamana' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Busoro' => ['Busoro' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Cyabakamyi' => ['Cyabakamyi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Kibirizi' => ['Kibirizi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Kigoma' => ['Kigoma' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Mukingo' => ['Mukingo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Muyira' => ['Muyira' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Ntyazo' => ['Ntyazo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Nyagisozi' => ['Nyagisozi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Ubumwe']],
                'Rwabicuma' => ['Rwabicuma' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
            ],
            'Nyaruguru' => [
                'Busanze' => ['Busanze' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Cyahinda' => ['Cyahinda' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Kibeho' => ['Kibeho' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Kivu' => ['Kivu' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Mata' => ['Mata' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Muganza' => ['Muganza' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Munini' => ['Munini' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Ngera' => ['Ngera' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Ngoma' => ['Ngoma' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Ubumwe']],
                'Nyabimata' => ['Nyabimata' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Nyagisozi' => ['Nyagisozi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intsinzi']],
                'Ruheru' => ['Ruheru' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Ruramba' => ['Ruramba' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Rusenge' => ['Rusenge' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
            ],
            'Ruhango' => [
                'Bweramana' => ['Bweramana' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Byimana' => ['Byimana' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Kabagari' => ['Kabagari' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Kinazi' => ['Kinazi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Kinihira' => ['Kinihira' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Mbuye' => ['Mbuye' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Mwendo' => ['Mwendo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Ntongwe' => ['Ntongwe' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Ruhango' => ['Ruhango' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Ubumwe']],
            ],
            'Karongi' => [
                'Bwishyura' => ['Bwishyura' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Gashari' => ['Gashari' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Gishyita' => ['Gishyita' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Gitesi' => ['Gitesi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Mubuga' => ['Mubuga' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Murambi' => ['Murambi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Murundi' => ['Murundi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Mutuntu' => ['Mutuntu' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Rubengera' => ['Rubengera' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Ubumwe']],
                'Rugabano' => ['Rugabano' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Ruganda' => ['Ruganda' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intsinzi']],
                'Rwankuba' => ['Rwankuba' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Twumba' => ['Twumba' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
            ],
            'Ngororero' => [
                'Bwira' => ['Bwira' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Gatumba' => ['Gatumba' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Hindiro' => ['Hindiro' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Kabaya' => ['Kabaya' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Kageyo' => ['Kageyo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Kavumu' => ['Kavumu' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Matyazo' => ['Matyazo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Muhanda' => ['Muhanda' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Muhororo' => ['Muhororo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Ubumwe']],
                'Ndaro' => ['Ndaro' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Ngororero' => ['Ngororero' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intsinzi']],
                'Nyange' => ['Nyange' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Sovu' => ['Sovu' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
            ],
            'Nyabihu' => [
                'Bigogwe' => ['Bigogwe' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Jenda' => ['Jenda' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Jomba' => ['Jomba' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Kabatwa' => ['Kabatwa' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Karago' => ['Karago' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Kintobo' => ['Kintobo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Mukamira' => ['Mukamira' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Muringa' => ['Muringa' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Rambura' => ['Rambura' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Ubumwe']],
                'Rugera' => ['Rugera' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Rurembo' => ['Rurembo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intsinzi']],
                'Shyira' => ['Shyira' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
            ],
            'Rutsiro' => [
                'Boneza' => ['Boneza' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Gihango' => ['Gihango' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Kigeyo' => ['Kigeyo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Kivumu' => ['Kivumu' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Manihira' => ['Manihira' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Mukura' => ['Mukura' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Murunda' => ['Murunda' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Musasa' => ['Musasa' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Mushonyi' => ['Mushonyi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Ubumwe']],
                'Mushubati' => ['Mushubati' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Nyabirasi' => ['Nyabirasi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intsinzi']],
                'Ruhango' => ['Ruhango' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Rusebeya' => ['Rusebeya' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
            ],
            'Rubavu' => [
                'Bugeshi' => ['Bugeshi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Busasamana' => ['Busasamana' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Cyanzarwe' => ['Cyanzarwe' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Gisenyi' => ['Gisenyi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Kanama' => ['Kanama' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Kanzenze' => ['Kanzenze' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Mudende' => ['Mudende' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Nyakiriba' => ['Nyakiriba' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Nyamyumba' => ['Nyamyumba' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Ubumwe']],
                'Nyundo' => ['Nyundo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Rubavu' => ['Rubavu' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intsinzi']],
                'Rugerero' => ['Rugerero' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
            ],
            'Burera' => [
                'Bungwe' => ['Bungwe' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Butaro' => ['Butaro' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Cyanika' => ['Cyanika' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Cyeru' => ['Cyeru' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Gahunga' => ['Gahunga' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Gatebe' => ['Gatebe' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Gitovu' => ['Gitovu' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Kagogo' => ['Kagogo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Kinoni' => ['Kinoni' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Ubumwe']],
                'Kinyababa' => ['Kinyababa' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Kivuye' => ['Kivuye' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intsinzi']],
                'Nemba' => ['Nemba' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Rugarama' => ['Rugarama' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Rugendabari' => ['Rugendabari' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Ruhunde' => ['Ruhunde' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Rusarabuye' => ['Rusarabuye' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Rwerere' => ['Rwerere' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
            ],
            'Gakenke' => [
                'Busengo' => ['Busengo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Coko' => ['Coko' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Cyabingo' => ['Cyabingo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Gakenke' => ['Gakenke' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Gashenyi' => ['Gashenyi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Janja' => ['Janja' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Kamubuga' => ['Kamubuga' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Karambo' => ['Karambo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Kivuruga' => ['Kivuruga' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Ubumwe']],
                'Mataba' => ['Mataba' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Minazi' => ['Minazi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intsinzi']],
                'Muhondo' => ['Muhondo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Muyongwe' => ['Muyongwe' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Muzo' => ['Muzo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Nemba' => ['Nemba' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Ruli' => ['Ruli' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Rusasa' => ['Rusasa' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Rushashi' => ['Rushashi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
            ],
            'Gicumbi' => [
                'Bukure' => ['Bukure' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Bwisige' => ['Bwisige' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Byumba' => ['Byumba' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Cyumba' => ['Cyumba' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Giti' => ['Giti' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Kaniga' => ['Kaniga' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Manyagiro' => ['Manyagiro' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Miyove' => ['Miyove' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Mukarange' => ['Mukarange' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Ubumwe']],
                'Muko' => ['Muko' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Mutete' => ['Mutete' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intsinzi']],
                'Nyamiyaga' => ['Nyamiyaga' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Nyankenke' => ['Nyankenke' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Rubaya' => ['Rubaya' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Rukomo' => ['Rukomo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Rushaki' => ['Rushaki' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Rutare' => ['Rutare' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Ruvune' => ['Ruvune' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Rwamiko' => ['Rwamiko' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Shangasha' => ['Shangasha' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
            ],
            'Musanze' => [
                'Busogo' => ['Busogo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Cyuve' => ['Cyuve' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Gacaca' => ['Gacaca' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Gashaki' => ['Gashaki' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Gataraga' => ['Gataraga' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Kimonyi' => ['Kimonyi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Kinigi' => ['Kinigi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Muhoza' => ['Muhoza' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Muko' => ['Muko' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Ubumwe']],
                'Musanze' => ['Musanze' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Nkotsi' => ['Nkotsi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intsinzi']],
                'Nyange' => ['Nyange' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Remera' => ['Remera' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Rwaza' => ['Rwaza' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Shingiro' => ['Shingiro' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
            ],
            'Rulindo' => [
                'Base' => ['Base' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Burega' => ['Burega' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Bushoki' => ['Bushoki' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Buyoga' => ['Buyoga' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Cyinzuzi' => ['Cyinzuzi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Cyungo' => ['Cyungo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Kinihira' => ['Kinihira' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Kisaro' => ['Kisaro' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Masoro' => ['Masoro' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Ubumwe']],
                'Mbogo' => ['Mbogo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Murambi' => ['Murambi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intsinzi']],
                'Ngoma' => ['Ngoma' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Ntarabana' => ['Ntarabana' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Rukozo' => ['Rukozo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Rusiga' => ['Rusiga' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Shyorongi' => ['Shyorongi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Tumba' => ['Tumba' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
            ],
            'Rusizi' => [
                'Bugarama' => ['Bugarama' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Butare' => ['Butare' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Bweyeye' => ['Bweyeye' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Gashonga' => ['Gashonga' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Giheke' => ['Giheke' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Gihundwe' => ['Gihundwe' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Gikundamvura' => ['Gikundamvura' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Gitambi' => ['Gitambi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Kamembe' => ['Kamembe' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Ubumwe']],
                'Muganza' => ['Muganza' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Mururu' => ['Mururu' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intsinzi']],
                'Nkanka' => ['Nkanka' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Nkombo' => ['Nkombo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Nkungu' => ['Nkungu' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Nyakabuye' => ['Nyakabuye' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Nyakarenzo' => ['Nyakarenzo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Nzahaha' => ['Nzahaha' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Rwimbogo' => ['Rwimbogo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
            ],
            'Nyamasheke' => [
                'Bushekeri' => ['Bushekeri' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Bushenge' => ['Bushenge' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Cyato' => ['Cyato' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
                'Gihombo' => ['Gihombo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Kagano' => ['Kagano' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intsinzi']],
                'Kanjongo' => ['Kanjongo' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Karambi' => ['Karambi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intore']],
                'Karengera' => ['Karengera' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Kirimbi' => ['Kirimbi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Ubumwe']],
                'Macuba' => ['Macuba' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intore']],
                'Mahembe' => ['Mahembe' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Intsinzi']],
                'Nyabitekeri' => ['Nyabitekeri' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Ubumwe']],
                'Rangiro' => ['Rangiro' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyerekezo', 'Intore']],
                'Ruharambuga' => ['Ruharambuga' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Ingenzi', 'Intsinzi']],
                'Shangi' => ['Shangi' => ['Amahoro', 'Imena'], 'Nyamirama' => ['Icyizere', 'Ubumwe']],
            ],
        ];

        foreach ($districts as $districtName => $sectors) {
            $district = Location::create([
                'type' => Location::TYPE_DISTRICT,
                'name' => $districtName,
                'parent_id' => $rwanda->id,
            ]);

            foreach ($sectors as $sectorName => $cells) {
                $sector = Location::create([
                    'type' => Location::TYPE_SECTOR,
                    'name' => $sectorName,
                    'parent_id' => $district->id,
                ]);

                foreach ($cells as $cellName => $villages) {
                    $cell = Location::create([
                        'type' => Location::TYPE_CELL,
                        'name' => $cellName,
                        'parent_id' => $sector->id,
                    ]);

                    foreach ($villages as $villageName) {
                        Location::create([
                            'type' => Location::TYPE_VILLAGE,
                            'name' => $villageName,
                            'parent_id' => $cell->id,
                        ]);
                    }
                }
            }
        }
    }
}
